package main

import (
	"bytes"
	"encoding/hex"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"

	"github.com/aurora-protocol/aurora-core/config"
	auroracrypto "github.com/aurora-protocol/aurora-core/crypto"
	"github.com/aurora-protocol/aurora-core/failure"
	"github.com/aurora-protocol/aurora-core/protocol"
	"github.com/aurora-protocol/aurora-core/registry"
	"github.com/aurora-protocol/aurora-core/transport"
	corevectors "github.com/aurora-protocol/aurora-core/vectors"
	"github.com/aurora-protocol/aurora-core/wire"
)

func main() {
	if len(os.Args) < 2 {
		usage()
		os.Exit(2)
	}
	var err error
	switch os.Args[1] {
	case "vectors":
		err = vectors(os.Args[2:], os.Stdout)
	case "capabilities":
		capabilities()
	case "active-probes":
		err = activeProbes(os.Stdout)
	case "wire-check":
		err = wireCheck(os.Stdout)
	case "check-config":
		if len(os.Args) != 3 {
			err = fmt.Errorf("check-config requires a path")
			break
		}
		err = checkConfig(os.Args[2])
	default:
		err = fmt.Errorf("unknown command %q", os.Args[1])
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func usage() {
	fmt.Fprintln(os.Stderr, "usage: auroractl <vectors [--check [path]]|capabilities|active-probes|wire-check|check-config>")
}

const structuralVectorSnapshotPath = "vectors/structural_vectors.txt"

func vectors(args []string, w io.Writer) error {
	switch len(args) {
	case 0:
		return writeVectors(w)
	case 1, 2:
		if args[0] != "--check" {
			return fmt.Errorf("vectors: unknown option %q", args[0])
		}
		path := structuralVectorSnapshotPath
		if len(args) == 2 {
			path = args[1]
		}
		return checkVectorSnapshot(path)
	default:
		return fmt.Errorf("vectors: too many arguments")
	}
}

func checkVectorSnapshot(path string) error {
	var generated bytes.Buffer
	if err := writeVectors(&generated); err != nil {
		return err
	}
	snapshot, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	if !bytes.Equal(snapshot, generated.Bytes()) {
		return fmt.Errorf("vectors: structural vector snapshot drift; regenerate %s", path)
	}
	return nil
}

func writeVectors(w io.Writer) error {
	control := auroracrypto.ControlAADInput{
		SelectedVersion:                 registry.Version20,
		SelectedSuite:                   registry.SuiteHybrid768AESGCM,
		MsgType:                         registry.MsgCoverCapsule1,
		RouteInstanceID:                 1,
		HandshakeBindingContext:         repeated(0xaa, 48),
		PreludeTranscriptHashForThisHop: repeated(0xbb, 48),
	}
	preimage, err := auroracrypto.ControlAADPreimage(control)
	if err != nil {
		return err
	}
	aad, err := auroracrypto.ControlAAD(control)
	if err != nil {
		return err
	}
	fmt.Fprintln(w, "control_aad_preimage:", hex.EncodeToString(preimage))
	fmt.Fprintln(w, "control_aad:", hex.EncodeToString(aad))

	route := auroracrypto.RouteWrapInput{
		RouteInstanceID:                1,
		HopIndex:                       1,
		PreviousHopRelayDescriptorHash: repeated(0x41, 48),
		NextRelayDescriptorHash:        repeated(0x42, 48),
		HintIssuerID:                   repeated(0x34, 16),
		RelayBucketID:                  repeated(0x35, 16),
		HintEpochID:                    7,
		HintSelector:                   repeated(0x31, 16),
		WrapSuiteID:                    registry.WrapSuiteRouteV1,
		WrapNonce:                      repeated(0x32, 16),
		HintSecret:                     repeated(0x33, 32),
	}
	context, key, iv, wrapAAD, sealed, err := auroracrypto.SealRoutePrelude(route, repeated(0x44, 16))
	if err != nil {
		return err
	}
	fmt.Fprintln(w, "route_prelude_wrap_context:", hex.EncodeToString(context))
	fmt.Fprintln(w, "route_prelude_wrap_key:", hex.EncodeToString(key))
	fmt.Fprintln(w, "route_prelude_wrap_iv:", hex.EncodeToString(iv))
	fmt.Fprintln(w, "route_wrap_aad:", hex.EncodeToString(wrapAAD))
	fmt.Fprintln(w, "route_wrap_ciphertext_tag:", hex.EncodeToString(sealed))

	pk := protocol.PublicKeyRecord{
		SignatureScheme: registry.SigECDSAP256SHA384DER,
		KeyEncoding:     registry.KeyP256SEC1Uncompressed,
		PublicKey:       repeated(0x04, 65),
	}
	encodedPK, err := wire.Encode(pk)
	if err != nil {
		return err
	}
	keyID := auroracrypto.Truncate128(auroracrypto.PreHashLabel("aurora v2.0 authority key id", encodedPK))
	akr := protocol.AuthorityKeyRecord{
		AuthorityID:    repeated(0x11, 16),
		AuthorityKeyID: keyID,
		AuthorityRole:  1,
		PublicKey:      pk,
		ValidFromUnix:  1700000000,
		ValidUntilUnix: 1800000000,
		KeyStatus:      registry.AuthorityActive,
		UsageFlags:     registry.UsageAllKnownAuthority,
	}
	encodedAKR, err := wire.Encode(akr)
	if err != nil {
		return err
	}
	fmt.Fprintln(w, "public_key_record:", hex.EncodeToString(encodedPK))
	fmt.Fprintln(w, "authority_key_id:", hex.EncodeToString(keyID))
	fmt.Fprintln(w, "authority_key_record:", hex.EncodeToString(encodedAKR))
	bundle, err := corevectors.GenerateStructuralBundle()
	if err != nil {
		return err
	}
	fmt.Fprintln(w, "object_signature:", bundle.ObjectSignature)
	fmt.Fprintln(w, "object_signature_unsigned:", bundle.ObjectSignatureUnsigned)
	fmt.Fprintln(w, "object_signature_hash:", bundle.ObjectSignatureHash)
	fmt.Fprintln(w, "directory_consensus:", bundle.DirectoryConsensus)
	fmt.Fprintln(w, "relay_descriptor:", bundle.RelayDescriptor)
	fmt.Fprintln(w, "cover_template:", bundle.CoverTemplate)
	fmt.Fprintln(w, "flow_open:", bundle.FlowOpen)
	fmt.Fprintln(w, "udp_target_confirm:", bundle.UDPTargetConfirm)
	fmt.Fprintln(w, "flow_close:", bundle.FlowClose)
	return nil
}

func capabilities() {
	capabilitiesReport(os.Stdout)
}

func capabilitiesReport(w io.Writer) {
	fmt.Fprintln(w, "implemented:")
	fmt.Fprintln(w, "- Section 9 wire scalar, opaque, vector, and struct encoding")
	fmt.Fprintln(w, "- Appendix A registries")
	fmt.Fprintln(w, "- Appendix B.4 and B.5 structural vectors")
	fmt.Fprintln(w, "- DirectoryConsensus, RelayDescriptor, CoverTemplate trust hashes, signature inputs, and strict ML-DSA authority quorum")
	fmt.Fprintln(w, "- AES-256-GCM, HKDF labels, SHA-384/SHA-512 suite hashes, ML-KEM wrappers, and ML-DSA verification")
	fmt.Fprintln(w, "- first-hop prelude transcript hashing, Finished messages, and application secret derivation")
	fmt.Fprintln(w, "- AccessHint, replay keys, packet protection, FrameBlock, FLOW_* validation, KEY_UPDATE")
	fmt.Fprintln(w, "- policy profiles, PAL scoring, PACE reference behavior, local config parsing")
	fmt.Fprintln(w, "not production-complete:")
	fmt.Fprintln(w, "- full real-crypto vector package, Privacy Pass production proof verification, cover-origin gateway, active-probe harness, platform adapters, DPI evaluation")
}

func activeProbes(w io.Writer) error {
	report, err := failure.RunActiveProbeHarness(failure.ActiveProbeCases())
	if err != nil {
		return err
	}
	fmt.Fprintf(w, "active_probe_baseline passed=%t cases=%d\n", report.Passed, len(report.Cases))
	fmt.Fprintf(w, "canonical %s\n", formatProbeSurface(report.CanonicalSurface))
	for _, finding := range report.Cases {
		fmt.Fprintf(w, "case %s passed=%t %s\n", finding.Name, finding.Passed, formatProbeSurface(finding.Surface))
	}
	if !report.Passed {
		return fmt.Errorf("active-probes failed neutrality check")
	}
	return nil
}

func wireCheck(w io.Writer) error {
	carriers := []transport.CarrierRequestInput{
		publicCarrierInput(registry.MethodWebH2Stream, "cover.example", "/assets/app.bin", http.Header{"Content-Type": []string{"application/octet-stream"}}),
		publicCarrierInput(registry.MethodWebH1WS, "cover.example", "/events/stream", http.Header{"User-Agent": []string{"Mozilla/5.0"}}),
		publicCarrierInput(registry.MethodShadowOrigin, "static.example", "/catalog/segment", http.Header{"Accept": []string{"*/*"}}),
		publicCarrierInput(registry.MethodWebH3Stream, "media.example", "/session/42", http.Header{"Content-Type": []string{"application/octet-stream"}}),
		publicH3DatagramCarrierInput(),
	}
	passed := true
	results := make([]wireCheckResult, 0, len(carriers))
	for _, input := range carriers {
		built, err := transport.BuildCarrierRequest(input)
		result := wireCheckResult{Name: input.Plan.Carrier.Name, Passed: err == nil}
		if err == nil {
			if marker := visibleCarrierMarker(built); marker != "" {
				result.Passed = false
				result.Detail = marker
			}
		} else {
			result.Detail = err.Error()
		}
		passed = passed && result.Passed
		results = append(results, result)
	}
	fmt.Fprintf(w, "public_wire_check passed=%t carriers=%d\n", passed, len(results))
	for _, result := range results {
		if result.Detail == "" {
			fmt.Fprintf(w, "carrier %s passed=%t\n", result.Name, result.Passed)
			continue
		}
		fmt.Fprintf(w, "carrier %s passed=%t detail=%s\n", result.Name, result.Passed, result.Detail)
	}
	if !passed {
		return fmt.Errorf("wire-check found forbidden public marker")
	}
	return nil
}

type wireCheckResult struct {
	Name   string
	Passed bool
	Detail string
}

func publicCarrierInput(method uint64, authority, path string, header http.Header) transport.CarrierRequestInput {
	return transport.CarrierRequestInput{
		Plan: transport.CarrierPlan{
			Carrier: transport.Carrier{MethodID: method, Name: publicCarrierName(method)},
			UDPMode: transport.UDPOverStreamFallback,
		},
		Template:       publicCarrierTemplate(method),
		RequestClassID: 1,
		NeedCapsule:    true,
		Scheme:         "https",
		Authority:      authority,
		Path:           path,
		Header:         header,
		Payload:        []byte{0x80, 0x01},
		WebSocketKeySeed: []byte{
			0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08,
			0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10,
		},
	}
}

func publicH3DatagramCarrierInput() transport.CarrierRequestInput {
	input := publicCarrierInput(registry.MethodWebH3ExtDgram, "media.example", "/items/live", http.Header{"Accept": []string{"*/*"}})
	input.Plan.UDPMode = transport.UDPNativeDatagram
	input.Template.H3Profile = protocol.H3CoverProfile{
		ProfileID:                  7,
		SupportsH3Datagram:         true,
		SupportsWebTransportH3:     true,
		WebTransportProfileID:      1,
		QUICDatagramRequired:       true,
		DatagramSizeDistributionID: repeated(0x22, 16),
		DatagramRateDistributionID: repeated(0x33, 16),
	}
	input.H3DatagramSettingsOK = true
	input.QUICMaxDatagramFrameSize = 1200
	return input
}

func publicCarrierTemplate(method uint64) protocol.CoverTemplate {
	return protocol.CoverTemplate{RequestClasses: []protocol.RequestClass{{
		ClassID:             1,
		ClassType:           registry.RequestGatewayOwnedSlot,
		AllowedMethodFamily: method,
		PathTemplateID:      repeated(0x11, 16),
		MayCarryPrelude:     true,
		MayCarryCapsule:     true,
	}}}
}

func publicCarrierName(method uint64) string {
	switch method {
	case registry.MethodWebH2Stream:
		return "web.h2.stream"
	case registry.MethodWebH1WS:
		return "web.h1.ws"
	case registry.MethodShadowOrigin:
		return "web.shadow-origin"
	case registry.MethodWebH3Stream:
		return "web.h3.stream"
	case registry.MethodWebH3ExtDgram:
		return "web.h3.ext-dgram"
	default:
		return "unknown"
	}
}

func visibleCarrierMarker(built transport.BuiltCarrierRequest) string {
	if built.Request == nil {
		return "missing request"
	}
	values := []string{built.Request.Host, built.Request.URL.Host, built.Request.URL.Path, built.ProtocolToken}
	for _, value := range values {
		if marker := forbiddenPublicWireMarker(value); marker != "" {
			return marker
		}
	}
	for key, values := range built.Request.Header {
		if marker := forbiddenPublicWireMarker(key); marker != "" {
			return marker
		}
		for _, value := range values {
			if marker := forbiddenPublicWireMarker(value); marker != "" {
				return marker
			}
		}
	}
	return ""
}

func forbiddenPublicWireMarker(value string) string {
	lower := strings.ToLower(value)
	for _, marker := range forbiddenPublicWireMarkers {
		if strings.Contains(lower, marker) {
			return marker
		}
	}
	return ""
}

var forbiddenPublicWireMarkers = []string{
	"aurora",
	"proxy",
	"vpn",
	"gfw",
	"china",
	"auth",
	"tunnel",
	"bridge",
	"relay",
	"policy",
	"adversarial",
	"dpi",
}

func formatProbeSurface(surface failure.ProbeSurface) string {
	return fmt.Sprintf("http_status=%d close_code=%d tls_alert=%d quic_close=%d websocket_close=%d timing_class=%s reflected_log=%s",
		surface.HTTPStatus,
		surface.CloseCode,
		surface.TLSAlertClass,
		surface.QUICCloseCode,
		surface.WebSocketCloseCode,
		surface.TimingClass,
		surface.ReflectedLog,
	)
}

func checkConfig(path string) error {
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()
	cfg, err := config.Parse(f)
	if err != nil {
		return err
	}
	fmt.Printf("ok profile=%s route=%s speed=%s effective=%s\n", cfg.Profile, cfg.Route, cfg.Speed, cfg.EffectiveProfile("normal").Name)
	return nil
}

func repeated(b byte, n int) []byte {
	out := make([]byte, n)
	for i := range out {
		out[i] = b
	}
	return out
}
