package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestActiveProbesCommandPrintsBaselineReport(t *testing.T) {
	var out bytes.Buffer
	if err := activeProbes(&out); err != nil {
		t.Fatal(err)
	}
	text := out.String()
	for _, want := range []string{
		"active_probe_baseline passed=true cases=13\n",
		"canonical http_status=0 close_code=0 tls_alert=0 quic_close=0 websocket_close=0 timing_class= reflected_log=\n",
		"case bad-access-hint passed=true http_status=0 close_code=0 tls_alert=0 quic_close=0 websocket_close=0 timing_class= reflected_log=\n",
		"case malformed-key-update passed=true http_status=0 close_code=0 tls_alert=0 quic_close=0 websocket_close=0 timing_class= reflected_log=\n",
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("active-probes output missing %q:\n%s", want, text)
		}
	}
	if strings.Contains(text, "passed=false") {
		t.Fatalf("active-probes output contains failing case:\n%s", text)
	}
}

func TestVectorsCommandPrintsFlowManagementVectors(t *testing.T) {
	var out bytes.Buffer
	if err := vectors(nil, &out); err != nil {
		t.Fatal(err)
	}
	text := out.String()
	for _, want := range []string{
		"flow_open: 420007020100045db8d82201bb01515151515151515151515151515151510000525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252020300\n",
		"udp_target_confirm: 070100045db8d82201bb5252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252520000003c0100\n",
		"flow_close: 07000100000000000000630004646f6e6500\n",
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("vectors output missing %q:\n%s", want, text)
		}
	}
}

func TestVectorsCheckAcceptsGeneratedSnapshot(t *testing.T) {
	var generated bytes.Buffer
	if err := vectors(nil, &generated); err != nil {
		t.Fatal(err)
	}
	snapshot := filepath.Join(t.TempDir(), "structural_vectors.txt")
	if err := os.WriteFile(snapshot, generated.Bytes(), 0o600); err != nil {
		t.Fatal(err)
	}

	var out bytes.Buffer
	if err := vectors([]string{"--check", snapshot}, &out); err != nil {
		t.Fatal(err)
	}
	if out.Len() != 0 {
		t.Fatalf("vectors --check wrote unexpected output: %q", out.String())
	}
}

func TestVectorsCheckRejectsSnapshotDrift(t *testing.T) {
	snapshot := filepath.Join(t.TempDir(), "structural_vectors.txt")
	if err := os.WriteFile(snapshot, []byte("stale\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	var out bytes.Buffer
	err := vectors([]string{"--check", snapshot}, &out)
	if err == nil {
		t.Fatalf("vectors --check accepted stale snapshot")
	}
	if !strings.Contains(err.Error(), "structural vector snapshot drift") {
		t.Fatalf("vectors --check drift error = %v", err)
	}
	if out.Len() != 0 {
		t.Fatalf("vectors --check wrote output on drift: %q", out.String())
	}
}

func TestCIWorkflowRunsVectorDriftCheck(t *testing.T) {
	workflow, err := os.ReadFile(filepath.Join("..", "..", ".github", "workflows", "ci.yml"))
	if err != nil {
		t.Fatal(err)
	}
	text := string(workflow)
	for _, want := range []string{
		"go test ./...",
		"go run ./cmd/auroractl vectors --check",
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("CI workflow missing %q:\n%s", want, text)
		}
	}
}
